### ISSUE TITLE
server-enviroment-setup

### ISSUE THREAD

**Issue by marianoheller** [chingu-voyage4/Bears-Team-20#12]

**Comment by cjlynch12** [comment]
- Set up Node.js environment
- Install required back end packages
-- Create react app
-- Dotenv
-- Passport
-- Passport-Google
--JsonWebToken
--Cookie-parser
--Mongoose

- Set up MLab datbase

**Comment by Vitao18** [comment]
Why are we going to need create react app on backend?

**Comment by cjlynch12** [comment]
not necessary specifically but for backend, but want to get it installed so that front end work can get started. Also includes web pack/Babel configs.

**Comment by marianoheller** [comment]
Ok, so I think he meant to initialize the client side of the repo using create-react-app, not actually installing CRA as a depency of the backend nor the frontend.

**Comment by cferreirasuazo** [comment]
are not we going to use express?
